theme: jekyll-theme-slate
title: UCL bioimage analysis collaborative hackday/BrainGlobe Hackathon
description: This hackday brings together the community and we will work in self-organising small groups on a bioimage-analysis-related software project for a day.
